# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ENSTA B COURS ET TD\UE 2.1\Projet Informatique\Interface_graphique.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(1116, 707)
        self.centralwidget = QtWidgets.QWidget(Interface)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 60, 931, 431))
        self.widget.setObjectName("widget")
        self.Depart = QtWidgets.QPushButton(self.centralwidget)
        self.Depart.setGeometry(QtCore.QRect(920, 600, 93, 28))
        self.Depart.setObjectName("Depart")
        self.ChoixVol = QtWidgets.QToolButton(self.centralwidget)
        self.ChoixVol.setGeometry(QtCore.QRect(100, 550, 110, 30))
        self.ChoixVol.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.ChoixVol.setAcceptDrops(False)
        self.ChoixVol.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.ChoixVol.setAutoRaise(False)
        self.ChoixVol.setArrowType(QtCore.Qt.NoArrow)
        self.ChoixVol.setObjectName("ChoixVol")
        self.ChoixAltitude = QtWidgets.QToolButton(self.centralwidget)
        self.ChoixAltitude.setGeometry(QtCore.QRect(100, 600, 110, 30))
        self.ChoixAltitude.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.ChoixAltitude.setObjectName("ChoixAltitude")
        self.ChoixDrones = QtWidgets.QToolButton(self.centralwidget)
        self.ChoixDrones.setGeometry(QtCore.QRect(380, 550, 150, 30))
        self.ChoixDrones.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.ChoixDrones.setObjectName("ChoixDrones")
        self.ChoixCarte = QtWidgets.QToolButton(self.centralwidget)
        self.ChoixCarte.setGeometry(QtCore.QRect(380, 600, 150, 30))
        self.ChoixCarte.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.ChoixCarte.setObjectName("ChoixCarte")
        Interface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        Interface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Interface)
        self.statusbar.setObjectName("statusbar")
        Interface.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(Interface)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "Cartographie par drones"))
        self.Depart.setText(_translate("Interface", "GO !"))
        self.ChoixVol.setText(_translate("Interface", "Mode de vol"))
        self.ChoixAltitude.setText(_translate("Interface", "Altitude"))
        self.ChoixDrones.setText(_translate("Interface", "Nombre de drones"))
        self.ChoixCarte.setText(_translate("Interface", "Carte choisie"))
        self.menuFichier.setTitle(_translate("Interface", "Fichier"))
        self.actionQuitter.setText(_translate("Interface", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interface = QtWidgets.QMainWindow()
    ui = Ui_Interface()
    ui.setupUi(Interface)
    Interface.show()
    sys.exit(app.exec_())
